apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ff-proxy.writer.name" . }}-nginx
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |+
    error_log /dev/stdout info;

    log_format upstreamlog '[$time_local] $remote_addr - $remote_user - $server_name $host to: $upstream_addr: $request $status upstream_response_time $upstream_response_time msec $msec request_time $request_time';
    access_log /dev/stdout upstreamlog;

    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        location /health {
            proxy_pass http://127.0.0.1:7000/health;
        }
    }