apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ff-proxy.writer.name" . }}-nginx
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |+
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        location /health {
            proxy_pass http://127.0.0.1:7000/health;
        }
    }